name: shiny-deploy
# test again

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
      shiny-deploy:
        runs-on: ubuntu-latest
        container: rocker/rstudio:4.1.0
        env:
           # This should not be necessary for installing from public repo's however install_github() fails without it.
          GITHUB_PAT: ${{ secrets.REPO_PAT }}

        steps:

          - name: Install System Dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y libz-dev icu-devtools libicu-dev libxml2 libxml2-dev zlib1g-dev libfontconfig1-dev libcairo2-dev

          - uses: actions/checkout@v2

          - name: Install R packages
            run: |
              # The binary package distributions from R Studio dramatically speed up installation time
              options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/focal/latest",
                 getOption("repos")))
              install.packages(c("shiny", "rsconnect", "tidyverse", "renv"))
              renv::restore()
            shell: Rscript {0}

          - name: Authorize and deploy app
            run: |
              branch<-Sys.getenv("GITHUB_REF_NAME")
              repo<-Sys.getenv("GITHUB_REPOSITORY")
              appName<-strsplit(repo, "/")[[1]][2]
              appName <- paste(appName, branch, sep="-")

              if(branch == "main") {
                appName <- "MODEL_AD_Explorer"
              }

              rsConnectUser <-"${{ secrets.RSCONNECT_USER }}"
              rsConnectToken <- "${{ secrets.RSCONNECT_TOKEN }}"
              rsConnectSecret <- "${{ secrets.RSCONNECT_SECRET }}"

              rsconnect::setAccountInfo(rsConnectUser, rsConnectToken, rsConnectSecret)
              rsconnect::deployApp(appName = appName, forceUpdate = TRUE)
              rsconnect::configureApp(appName, size="xxxlarge")
            shell: Rscript {0}
